### ISSUE TITLE
Setup GitHub Action

### ISSUE THREAD

**Issue by nikeee** [jcamiel/quiz#3]
I created an action to make setting up Hurl simpler: https://github.com/nikeee/setup-hurl

In case you want to try it out, you can replace this:
```yaml
      - name: Integration test
        run: |
          curl -LO https://github.com/Orange-OpenSource/hurl/releases/download/1.5.0/hurl_1.5.0_amd64.deb
          sudo dpkg -i hurl_1.5.0_amd64.deb
          bin/integration.sh
```
with this:
```yaml
      - uses: nikeee/setup-hurl@v1
      - name: Integration test
        run: bin/integration.sh
```
Feel free to close this issue; it's just a shameless plug. :)
